import './style.css'

type State = 'Newly joined' | 'Active' | 'Highly active' | 'At risk' | 'Dormant'
type Member = { id: number; name: string; initials: string; role: string; space: string; state: State; last: string; activities: number; owner: string; nextAction: string; color: string; history: string[] }

const members: Member[] = [
  { id: 1, name: 'Aisha Mensah', initials: 'AM', role: 'Product builder', space: 'Peer Circles', state: 'Highly active', last: 'Today', activities: 18, owner: 'Maya', nextAction: 'Invite to host a circle', color: '#e36b46', history: ['Shared a funding resource in Peer Circles', 'Joined Founder Friday', 'Welcomed two new members'] },
  { id: 2, name: 'Theo Martins', initials: 'TM', role: 'Freelance designer', space: 'Skill Swaps', state: 'Active', last: 'Yesterday', activities: 9, owner: 'Maya', nextAction: 'Check in after workshop', color: '#487b8c', history: ['Offered brand feedback in Skill Swaps', 'Attended Creative Ops workshop'] },
  { id: 3, name: 'Priya Shah', initials: 'PS', role: 'Community researcher', space: 'Open Forum', state: 'Newly joined', last: '2 days ago', activities: 2, owner: 'Jordan', nextAction: 'Make a peer introduction', color: '#b17a45', history: ['Introduced herself in Open Forum', 'Saved a discussion on inclusive research'] },
  { id: 4, name: 'Jon Bell', initials: 'JB', role: 'Operations lead', space: 'Office Hours', state: 'At risk', last: '12 days ago', activities: 6, owner: 'Maya', nextAction: 'Send a human check-in', color: '#8166a8', history: ['Booked an Office Hours slot', 'Asked about member benefits'] },
  { id: 5, name: 'Nia Okafor', initials: 'NO', role: 'Social entrepreneur', space: 'Founder Friday', state: 'Highly active', last: 'Today', activities: 22, owner: 'Jordan', nextAction: 'Nominate for member spotlight', color: '#c45a70', history: ['Posted a grant opportunity', 'Attended Founder Friday', 'Introduced Ravi to the finance circle'] },
  { id: 6, name: 'Marcus Lee', initials: 'ML', role: 'Impact investor', space: 'Open Forum', state: 'Active', last: '3 days ago', activities: 11, owner: 'Maya', nextAction: 'Invite to the capital Q&A', color: '#5b8f78', history: ['Answered a question about impact metrics', 'Commented on a community thread'] },
  { id: 7, name: 'Ravi Kumar', initials: 'RK', role: 'Early-stage founder', space: 'Peer Circles', state: 'Active', last: '4 days ago', activities: 8, owner: 'Jordan', nextAction: 'Share peer circle options', color: '#3f75a3', history: ['Joined a peer circle', 'Reacted to a founder introduction'] },
  { id: 8, name: 'Sofia Chen', initials: 'SC', role: 'Finance educator', space: 'Skill Swaps', state: 'Highly active', last: 'Yesterday', activities: 16, owner: 'Maya', nextAction: 'Ask about leading a session', color: '#d4934d', history: ['Hosted a budgeting skill swap', 'Commented on three discussions'] },
  { id: 9, name: 'Daniel Reed', initials: 'DR', role: 'Marketing strategist', space: 'Open Forum', state: 'Dormant', last: '31 days ago', activities: 3, owner: 'Jordan', nextAction: 'Offer a low-friction re-entry', color: '#707786', history: ['Joined the community', 'Read the welcome thread'] },
  { id: 10, name: 'Leila Haddad', initials: 'LH', role: 'Program manager', space: 'Office Hours', state: 'Active', last: '5 days ago', activities: 10, owner: 'Maya', nextAction: 'Follow up on office hours', color: '#9e6b82', history: ['Booked office hours', 'Shared an event recap'] },
  { id: 11, name: 'Owen Wright', initials: 'OW', role: 'Data analyst', space: 'Peer Circles', state: 'At risk', last: '16 days ago', activities: 5, owner: 'Jordan', nextAction: 'Ask what would be useful now', color: '#4d847e', history: ['Joined a peer circle', 'Reacted to a resource'] },
  { id: 12, name: 'Amara Joseph', initials: 'AJ', role: 'Nonprofit founder', space: 'Founder Friday', state: 'Highly active', last: 'Today', activities: 20, owner: 'Maya', nextAction: 'Connect with impact peers', color: '#c7713f', history: ['Attended Founder Friday', 'Shared a hiring resource', 'Welcomed a new member'] },
  { id: 13, name: 'Eli Novak', initials: 'EN', role: 'Product manager', space: 'Skill Swaps', state: 'Newly joined', last: '1 day ago', activities: 1, owner: 'Jordan', nextAction: 'Invite to a first event', color: '#5c729b', history: ['Completed onboarding profile'] },
  { id: 14, name: 'Grace Kim', initials: 'GK', role: 'Creative director', space: 'Open Forum', state: 'Dormant', last: '45 days ago', activities: 4, owner: 'Maya', nextAction: 'Review before outreach', color: '#8a7a5e', history: ['Posted an introduction', 'Saved a discussion'] },
  { id: 15, name: 'Samira Cole', initials: 'SC', role: 'Policy fellow', space: 'Office Hours', state: 'Active', last: '6 days ago', activities: 7, owner: 'Jordan', nextAction: 'Share policy circle details', color: '#bf6370', history: ['Attended an office hour', 'Asked a thoughtful question'] },
]

const stateClass = (state: State) => state.toLowerCase().replace(' ', '-')
const counts = () => members.reduce<Record<string, number>>((all, member) => ({ ...all, [member.state]: (all[member.state] || 0) + 1 }), {})
let activeView = 'Overview'
let selectedMember: Member | null = null
let listFilters = { search: '', state: '', space: '', owner: '', recency: '' }
let connectedExcelFile: FileSystemFileHandle | null = null
const savedMembers = localStorage.getItem('common-ground-members')
if (savedMembers) { members.splice(0, members.length, ...JSON.parse(savedMembers)) }
const saveMembers = () => { localStorage.setItem('common-ground-members', JSON.stringify(members)); void syncExcelFile(); void syncCodebaseFile() }
const csvCell = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`
function membersCsv() { const headers = ['id', 'name', 'role', 'space', 'state', 'last', 'activities', 'owner', 'nextAction', 'history']; return [headers, ...members.map(m => [m.id, m.name, m.role, m.space, m.state, m.last, m.activities, m.owner, m.nextAction, m.history.join(' | ')] )].map(line => line.map(csvCell).join(',')).join('\n') }
async function syncCodebaseFile() { try { await fetch('/api/members-sync', { method: 'POST', headers: { 'Content-Type': 'text/csv' }, body: membersCsv() }); } catch { /* Production deployments may not expose the local file endpoint. */ } }
function exportMembers() { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([membersCsv()], { type: 'text/csv;charset=utf-8' })); link.download = 'common-ground-members.csv'; link.click(); URL.revokeObjectURL(link.href) }
async function syncExcelFile() { if (!connectedExcelFile) return; const writable = await connectedExcelFile.createWritable(); await writable.write(membersCsv()); await writable.close() }
async function generateAiInsight(outputId = 'ai') { if (!selectedMember) return; const output = document.querySelector<HTMLElement>(`#${outputId}`); if (!output) return; output.textContent = 'Gemini is generating an insight...'; try { const response = await fetch('/api/ai-insight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: selectedMember.name, space: selectedMember.space, history: selectedMember.history }) }); if (!response.ok) throw new Error('AI unavailable'); const result = await response.json() as { text: string }; output.innerText = `${result.text}\n\nGemini AI suggestion is generated from recorded activity and requires human review.` } catch { output.innerHTML = '<b>Simulated fallback:</b> Invite them to a relevant upcoming conversation in their active space. Human review required.' } }
function importMembers(file: File) { const reader = new FileReader(); reader.onload = () => { const lines = String(reader.result).split(/\r?\n/).filter(Boolean).slice(1); const imported = lines.map(line => line.split(/,(?=")/).map(cell => cell.replace(/^"|"$/g, '').replaceAll('""', '"'))).filter(cells => cells.length >= 9).map(cells => ({ id: Number(cells[0]) || Date.now(), name: cells[1], initials: cells[1].split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase(), role: cells[2], space: cells[3], state: cells[4] as State, last: cells[5], activities: Number(cells[6]) || 0, owner: cells[7], nextAction: cells[8], color: '#687f92', history: (cells[9] || '').split(' | ').filter(Boolean) })); if (imported.length) { members.splice(0, members.length, ...imported); saveMembers(); render() } }; reader.readAsText(file) }

const row = (m: Member) => `<button class="member-row" data-member="${m.id}"><span class="avatar" style="--avatar:${m.color}">${m.initials}</span><span class="member-name"><strong>${m.name}</strong><small>${m.role}</small></span><span>${m.space}</span><span class="state-pill ${stateClass(m.state)}">${m.state}</span><span>${m.last}</span><b>↗</b></button>`
const tableHead = '<div class="table-head"><span>MEMBER</span><span>SPACE</span><span>STATE</span><span>LAST ACTIVE</span><span></span></div>'
const navItems = ['Overview', 'Members', 'Follow-up', 'New members', 'Highly active', 'At risk + dormant']
function overviewInsight() { return `<section class="ai-overview"><div><p class="eyebrow">AI-ASSISTED MEMBER INSIGHT</p><h2>Turn activity into context</h2><p>Gemini summarises recorded activity, identifies the relevant community space, and suggests one human-led next step.</p></div><div class="ai-controls"><select id="overview-member">${members.map(m => `<option value="${m.id}">${m.name} · ${m.space}</option>`).join('')}</select><button class="primary" id="overview-ai-run">✦ Run Gemini insight</button><p id="overview-ai-output">Uses recorded activity only. Requires human review.</p></div></section>` }
function openAddMember() { const modal = document.createElement('div'); modal.className = 'backdrop'; modal.innerHTML = '<section class="modal add-modal"><button class="close" type="button" id="cancel-add">×</button><p class="eyebrow">NEW COMMUNITY MEMBER</p><h2>Add member</h2><form id="add-form"><label>Name<input name="name" required placeholder="Full name" /></label><label>Role<input name="role" required placeholder="Role or focus" /></label><label>Community space<select name="space"><option>Open Forum</option><option>Peer Circles</option><option>Skill Swaps</option><option>Office Hours</option><option>Founder Friday</option></select></label><label>Owner<select name="owner"><option>Maya</option><option>Jordan</option><option>Unassigned</option></select></label><label>Next action<input name="nextAction" value="Welcome member" required /></label><div class="form-actions"><button class="secondary" type="button" id="cancel-add-button">Cancel</button><button class="primary" type="submit">Add member</button></div></form></section>'; document.body.append(modal); const close = () => modal.remove(); modal.querySelector('#cancel-add')?.addEventListener('click', close); modal.querySelector('#cancel-add-button')?.addEventListener('click', close); modal.querySelector('#add-form')?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.target as HTMLFormElement); const name = String(form.get('name')); members.push({ id: Date.now(), name, initials: name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase(), role: String(form.get('role')), space: String(form.get('space')), state: 'Newly joined', last: 'Just now', activities: 0, owner: String(form.get('owner')), nextAction: String(form.get('nextAction')), color: '#687f92', history: ['Added to the community CRM'] }); saveMembers(); close(); render() }) }
function render() {
  const c = counts(); const baseMembers = activeView === 'Overview' ? members.slice(0, 7) : members.filter(m => activeView === 'Members' || (activeView === 'Follow-up' ? ['At risk', 'Dormant'].includes(m.state) : activeView === 'New members' ? m.state === 'Newly joined' : activeView === 'Highly active' ? m.state === 'Highly active' : ['At risk', 'Dormant'].includes(m.state))); const filtered = activeView === 'Overview' ? baseMembers : baseMembers.filter(m => (!listFilters.search || `${m.name} ${m.role} ${m.space}`.toLowerCase().includes(listFilters.search.toLowerCase())) && (!listFilters.state || m.state === listFilters.state) && (!listFilters.space || m.space === listFilters.space) && (!listFilters.owner || m.owner === listFilters.owner) && (!listFilters.recency || (listFilters.recency === '7' ? ['Today', 'Yesterday'].includes(m.last) : listFilters.recency === '30' ? !['31 days ago', '45 days ago'].includes(m.last) : ['31 days ago', '45 days ago'].includes(m.last))))
  document.querySelector<HTMLDivElement>('#app')!.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand">CRM</div><div class="workspace">WORKSPACE　⌄</div><nav>${navItems.map(item => `<button class="nav-item ${item === activeView ? 'active' : ''}" data-view="${item}">◈　${item}<b>${item === 'Follow-up' ? (c['At risk'] || 0) + (c.Dormant || 0) : ''}</b></button>`).join('')}</nav><button class="nav-item help" data-view="Help">?　 Help & rules</button><div class="profile"><span class="avatar">MC</span><span><strong>Maya Chen</strong><small>Community manager</small></span></div></aside><main><header><div><p class="eyebrow">COMMUNITY CRM / SEPTEMBER 2024</p><h1>${activeView === 'Overview' ? 'Community pulse' : activeView}</h1><p class="subtitle">A clear view of who is showing up, and who needs a thoughtful nudge.</p></div><div class="header-actions"><button class="secondary" id="import-button">↓ Import</button><input type="file" id="import-file" accept=".csv,text/csv" hidden><button class="secondary" id="export">↑ Export</button><button class="primary" id="add">＋ Add member</button></div></header><div class="excel-status" id="excel-status">Latest changes sync to data/members.csv</div>${activeView === 'Help' ? help() : activeView === 'Overview' ? overview(c) : list(filtered)}${activeView === 'Overview' ? overviewInsight() : ''}</main></div>${selectedMember ? detail(selectedMember) : ''}`
  document.querySelectorAll<HTMLElement>('[data-view]').forEach(e => e.onclick = () => { activeView = e.dataset.view || 'Overview'; listFilters = { search: '', state: '', space: '', owner: '', recency: '' }; render() }); document.querySelectorAll<HTMLElement>('[data-member]').forEach(e => e.onclick = () => { selectedMember = members.find(m => m.id === +e.dataset.member!) || null; render() }); document.querySelector('#add')?.addEventListener('click', openAddMember); document.querySelector('#export')?.addEventListener('click', exportMembers); document.querySelector('#import-button')?.addEventListener('click', () => document.querySelector<HTMLInputElement>('#import-file')?.click()); document.querySelector('#import-file')?.addEventListener('change', e => { const file = (e.target as HTMLInputElement).files?.[0]; if (file) importMembers(file) }); document.querySelector('#close')?.addEventListener('click', () => { selectedMember = null; render() }); document.querySelector('#log')?.addEventListener('click', () => { if (!selectedMember) return; const activity = prompt('What meaningful activity should be recorded?'); if (!activity) return; selectedMember.activities += 1; selectedMember.last = 'Just now'; selectedMember.history.unshift(activity); saveMembers(); render() }); document.querySelector('#owner-select')?.addEventListener('change', e => { if (selectedMember) { selectedMember.owner = (e.target as HTMLSelectElement).value; saveMembers(); render() } }); document.querySelector('#edit-action')?.addEventListener('click', () => { if (!selectedMember) return; const action = prompt('Next action', selectedMember.nextAction); if (action) selectedMember.nextAction = action; saveMembers(); render() }); document.querySelector('#delete-member')?.addEventListener('click', () => { if (!selectedMember) return; const deletedId = selectedMember.id; members.splice(members.findIndex(m => m.id === deletedId), 1); selectedMember = null; saveMembers(); render() }); document.querySelector('#suggest')?.addEventListener('click', () => { document.querySelector('#ai')!.innerHTML = '<b>Simulated suggestion:</b> Invite them to a relevant upcoming conversation in their active space. Human review required.' }); document.querySelector('#search')?.addEventListener('input', e => { listFilters.search = (e.target as HTMLInputElement).value; render() }); ['state', 'space', 'owner', 'recency'].forEach(id => document.querySelector(`#${id}`)?.addEventListener('change', e => { listFilters[id as keyof typeof listFilters] = (e.target as HTMLSelectElement).value; render() })); document.querySelectorAll<HTMLElement>('[data-clear-filter]').forEach(e => e.onclick = () => { listFilters[e.dataset.clearFilter as keyof typeof listFilters] = ''; render() }); document.querySelector('#clear-filters')?.addEventListener('click', () => { listFilters = { search: '', state: '', space: '', owner: '', recency: '' }; render() })
}
function overview(c: Record<string, number>) { return `<section class="metrics"><div class="metric coral"><span>Total members</span><strong>15</strong><small>+3 since August</small></div><div class="metric mint"><span>Active this month</span><strong>${(c.Active || 0) + (c['Highly active'] || 0)}</strong><small>Meaningful participation</small></div><div class="metric gold"><span>Need follow-up</span><strong>${(c['At risk'] || 0) + (c.Dormant || 0)}</strong><small>Assigned to owners</small></div><div class="metric lilac"><span>Activities logged</span><strong>${members.reduce((n, m) => n + m.activities, 0)}</strong><small>Across 6 community spaces</small></div></section><section class="columns"><div class="panel"><div class="panel-head"><div><h2>Member directory</h2><p>Recent activity across your community</p></div><button data-view="Members">View all members →</button></div>${tableHead}${members.slice(0, 7).map(row).join('')}</div><aside><div class="panel"><div class="panel-head"><div><h2>Needs your attention</h2><p>Small actions, meaningful returns</p></div></div>${members.filter(m => ['At risk', 'Dormant'].includes(m.state)).slice(0, 3).map(m => `<button class="attention" data-member="${m.id}"><span class="avatar" style="--avatar:${m.color}">${m.initials}</span><span><b>${m.name}</b><small>${m.nextAction}</small></span>●</button>`).join('')}<button class="follow" data-view="Follow-up">Open follow-up queue　→</button></div><div class="panel spaces"><h2>Community spaces</h2><p>Where energy is gathering</p>${[['Founder Friday', 62], ['Peer Circles', 48], ['Skill Swaps', 35], ['Office Hours', 24]].map(([n, v]) => `<div class="space"><span>${n}</span><b>${v}%</b><i><u style="width:${v}%"></u></i></div>`).join('')}</div></aside></section>` }
function list(items: Member[]) { const chips = Object.entries(listFilters).filter(([, value]) => value).map(([key, value]) => `<button class="filter-chip" data-clear-filter="${key}">${value} ×</button>`).join(''); const rows = items.length ? items.map(row).join('') : '<div class="empty-state"><strong>No members match these filters.</strong><span>Try clearing a filter or searching for another member.</span><button class="secondary" id="clear-filters">Clear filters</button></div>'; return `<div class="toolbar"><div class="search">⌕ <input id="search" value="${listFilters.search}" placeholder="Search name, role, space..." /></div><select id="state"><option value="">All states</option>${['Newly joined', 'Active', 'Highly active', 'At risk', 'Dormant'].map(s => `<option ${listFilters.state === s ? 'selected' : ''}>${s}</option>`).join('')}</select><select id="space"><option value="">All spaces</option>${[...new Set(members.map(m => m.space))].map(s => `<option ${listFilters.space === s ? 'selected' : ''}>${s}</option>`).join('')}</select><select id="owner"><option value="">All owners</option>${['Maya', 'Jordan', 'Unassigned'].map(s => `<option ${listFilters.owner === s ? 'selected' : ''}>${s}</option>`).join('')}</select><select id="recency"><option value="">Any recency</option><option value="7" ${listFilters.recency === '7' ? 'selected' : ''}>Last 7 days</option><option value="30" ${listFilters.recency === '30' ? 'selected' : ''}>Last 30 days</option><option value="old" ${listFilters.recency === 'old' ? 'selected' : ''}>31+ days ago</option></select></div><div class="filter-row">${chips || '<span>Use filters to find members needing a human follow-up.</span>'}<strong>${items.length} result${items.length === 1 ? '' : 's'}</strong>${chips ? '<button class="clear-link" id="clear-filters">Clear all</button>' : ''}</div><section class="panel list"><div class="panel-head"><div><h2>${items.length} members</h2><p>Activity scores reflect community participation, not buying intent.</p></div></div>${tableHead}${rows}</section>` }
function help() { return `<section class="help-grid"><div class="panel help-card"><span class="help-icon">✦</span><h2>Built for community care</h2><p>Custom TypeScript + Vite prototype for managing fictional Friends of Finance members.</p><h3>Activity-state rules</h3><p><b>Newly joined</b>: under 7 days. <b>Highly active</b>: 12+ activities in 30 days. <b>Active</b>: 5–11. <b>At risk</b>: 8–21 days since activity. <b>Dormant</b>: 22+ days.</p></div><div class="panel help-card"><span class="help-icon">◎</span><h2>AI, with a human in the loop</h2><p>The simulated suggestion uses only recorded activity. It never sends messages, invents personalisation, or scores buying intent. Any commercial signal would stay separate and require review.</p><h3>Testing steps</h3><p>Add or open a member, record activity, search, filter, and check the follow-up queue. Data is fictional and local.</p></div></section>` }
function detail(m: Member) { return `<div class="backdrop"><section class="modal"><button class="close" id="close">×</button><div class="detail-head"><span class="avatar large" style="--avatar:${m.color}">${m.initials}</span><div><p class="eyebrow">MEMBER PROFILE</p><h2>${m.name}</h2><p>${m.role} · ${m.space}</p></div><span class="state-pill ${stateClass(m.state)}">${m.state}</span></div><div class="detail-stats"><span>ACTIVITIES <b>${m.activities}</b></span><span>LAST ACTIVE <b>${m.last}</b></span><span>OWNER <b>${m.owner}</b></span></div><div class="detail-grid"><div><h3>Activity history</h3>${m.history.map(h => `<p class="event">●　${h}<small>Recorded recently</small></p>`).join('')}<button class="secondary" id="log">＋ Record activity</button></div><div class="next"><p class="eyebrow">MANAGEMENT</p><label class="field-label">Owner<select id="owner-select">${['Maya', 'Jordan', 'Unassigned'].map(owner => `<option ${m.owner === owner ? 'selected' : ''}>${owner}</option>`).join('')}</select></label><p class="eyebrow action-label">NEXT ACTION</p><h3>${m.nextAction}</h3><button class="secondary" id="edit-action">Edit next action</button><button class="primary full" id="suggest">✦ Member insight <small>GEMINI AI</small></button><p id="ai" class="ai">Based only on recorded activity. Human review required.</p><button class="delete-button" id="delete-member">Delete member</button></div></div></section></div>` }
render()
document.addEventListener('click', event => { if ((event.target as HTMLElement).id === 'suggest') void generateAiInsight() })
document.addEventListener('click', event => { if ((event.target as HTMLElement).id === 'overview-ai-run') { const memberId = Number(document.querySelector<HTMLSelectElement>('#overview-member')?.value); selectedMember = members.find(member => member.id === memberId) || null; void generateAiInsight('overview-ai-output') } })
